version: '2.2'

services:
  edgeapp:
    image: openjdk:11.0.8-jre
    container_name: client_tomcat
    restart: always
    network_mode: "host"
    #tty: "true"
    volumes:
      - ./EsmEdgeApp.jar:/EsmEdgeApp.jar
      - ./location.properties:/location.properties
      - ../.version:/.version:ro
    environment:
      TZ: Asia/Taipei
      INTERFACE_NAME: $WEB_IF_NAME
      API_KEY_VALUE: $API_KEY_VALUE
      ORG_3_CODE: $ORG_3_CODE
      DEV_MODE: ${DEV_MODE:-no}
    command: "java -jar /EsmEdgeApp.jar" #  -Xmx3g"
