version: '2.1'
services:
    fluentd:
        image: csti/fluentd:v4
        build:
            context: "./fluentd_image/"
            dockerfile: "Dockerfile"
        volumes:
            - "$FLUENTD_BUFFER_PATH:/fluentd/Buffers"
            - "./conf/fluent.conf:/fluentd/etc/fluent.conf"
            - "/usr/share/zoneinfo/ROC:/etc/localtime:ro" 
            - "$SURICATA_LOG_PATH:/fluentd/suricata/"
        network_mode: host
        restart: always
