version: '3.1'

services:
  PacketAnalyze:
    image: openjdk:11.0.8-jre
    restart: always
    network_mode: "host"
    tty: true
    volumes:
      - ./Packet_analyze/CICFlowMeter.jar:/CICFlowMeter.jar
      - ./Packet_analyze/libjnetpcap.so:/usr/local/openjdk-11/lib/libjnetpcap.so
      - ./Packet_analyze/libpcap.so.1.9.1:/usr/local/openjdk-11/lib/libpcap.so.0.8
    environment:
      - "ES_IP=localhost"
      - "ES_PORT=19200"
      - "ES_INDEX_PREFIX=cic_"
      - "READ_LOCAL_FILE=FALSE"
      - "NETWORK_INTERFACE=$IF_NAME"
      - "WRITE_TO_CSV=FALSE"
      - "BULK_WRITE_LEN=10"
    command: "java -jar /CICFlowMeter.jar"

  # OMP:
  #   image: csti/omp:v1
  #   build:
  #     context: "./OMP/"
  #     dockerfile: "Dockerfile"
  #   restart: always
  #   volumes:
  #   - "./OMP/code/:/usr/src/omp/code/"
  #   - "./OMP/data/:/usr/src/omp/code/data/"

  Winlog:
    image: csti/winlog:v1.2
    build:
      context: "./Winlog/"
      dockerfile: "Dockerfile"
    container_name: winlog
    networks:
      - esm
    restart: always

  ETA_Attack:
    image: csti/eta:latest
    build:
      context: "./ETA/"
      dockerfile: "Dockerfile"
    container_name: eta_attack
    volumes:
      - "./ETA/ETA-ATTACK/:/ETA-ATTACK/"
    command: "python /ETA-ATTACK/eta_attack_api.py"
    networks:
      - esm
    restart: always 

  ETA_Malware:
    image: csti/eta:latest
    build:
      context: "./ETA/"
      dockerfile: "Dockerfile"
    container_name: eta_malware
    volumes:
      - "./ETA/ETA-MALWARE/:/ETA-MALWARE/"
    command: "python /ETA-MALWARE/eta_malware_api.py"
    networks:
      - esm
    restart: always

networks:
  esm:
    external:
      name: esm_network