version: "3.3"

services:
  cron:
    image: csti/cron:Crontab
    container_name: cron 
    build:
      context: "./docker_image/"
      dockerfile: "Dockerfile"
    volumes:
      #- "$FLUENTD_LOG_PATH:/fluentd_log"
      - "$ES_VOLUME_PATH:/es_volume"
      - "$SURICATA_LOG_PATH:/suricata_log"
      - "../Suricata/suricata/rules:/Suricata_rules/rules"
      - "/usr/share/zoneinfo/ROC:/etc/localtime:ro"
      - "./scripts:/scripts:ro"
      - "/etc/hostname:/hostname:ro"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - ../SecBuzzerESM.env:/.env:ro
      - "$FLUENTD_BUFFER_PATH/Logs/:/Logs/"
      - "$FLUENTD_LOG_PATH:/LogsCompress"
    environment:
      ESM_API: ${API_KEY_VALUE:-NONE}
      ORG_1_CODE: ${ORG_1_CODE:-TEST}
      ORG_2_CODE: ${ORG_2_CODE:-TEST}
      ORG_3_CODE: ${ORG_3_CODE:-NONE}
      DEV: ${DEV_MODE:-no}
    networks:
      - esm
    restart: unless-stopped

networks:
  esm:
    external:
      name: esm_network